 version: '2'
 services:
   db:
     image: postgres
   app:
     build: .
     volumes:
       - .:/code
     ports:
       - "8000:8000"
     depends_on:
       - db
     command: ./docker-start-app.sh
     
     # Uncomment the command below, and comment out the one above for troubleshooting
     # command: bash -c "while true; do echo 'long running op for testing...'; sleep 2; done"

