# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import functools
import ticket.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedBall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(validators=[functools.partial(ticket.validators._within_range, *(), **{'highbound': 26, 'lowbound': 1})])),
                ('hive_drone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hive.Drone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhiteBall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(validators=[functools.partial(ticket.validators._within_range, *(), **{'highbound': 69, 'lowbound': 1})])),
                ('hive_drone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hive.Drone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='whiteball',
            unique_together=set([('hive_drone_id', 'value')]),
        ),
        migrations.AlterUniqueTogether(
            name='redball',
            unique_together=set([('hive_drone_id', 'value')]),
        ),
    ]
